{
 "title": "perfSONAR Host Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "{\"find\":\"terms\", \"field\":\"meta.uname.nodename.keyword\", \"size\": 1}"
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 3 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nService Up/Down Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Current Service Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_systemd_unit_state.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: localhost AND !meta.labels.name.keyword: perfsonar-generate_motd.service AND !meta.labels.name.keyword: perfsonar-configure_nic_parameters.service AND values.node_systemd_unit_state: * AND meta.labels.state.keyword: active",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "History of perfSONAR Service Status",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_systemd_unit_state.val",
       "id": "1",
       "type": "min"
      }
     ],
     "query": "meta.id.keyword: localhost AND !meta.labels.name.keyword: perfsonar-generate_motd.service AND !meta.labels.name.keyword: perfsonar-configure_nic_parameters.service AND values.node_systemd_unit_state: * AND meta.labels.state.keyword: active",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 15 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nHost Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "OS Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.os.pretty_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.uname.release.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.uname.machine.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.id.keyword: localhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_memory_MemAvailable_bytes.val",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.node_memory_MemTotal_bytes.val",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: localhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "CPU Utilization",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_cpu_seconds_total.rate",
       "id": "1",
       "settings": { "script": "1 - _value" },
       "type": "avg"
      }
     ],
     "query": "meta.id.keyword: localhost AND meta.labels.mode.keyword: idle",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.cpu.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_softnet_processed_total.rate",
       "id": "1",
       "settings": { "percents": [ "50" ] },
       "type": "percentiles"
      }
     ],
     "query": "meta.id.keyword: localhost AND values.node_softnet_processed_total: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "{{term meta.labels.device.keyword}} Incoming Traffic",
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_network_receive_bytes_total.rate",
       "id": "1",
       "settings": { "script": "_value * 8" },
       "type": "avg"
      }
     ],
     "query": "meta.id.keyword: localhost AND values.node_network_protocol_type.val:* AND !values.node_network_protocol_type.val:  772",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term meta.labels.device.keyword}} Outgoing Traffic",
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_network_transmit_bytes_total.rate",
       "id": "1",
       "settings": { "script": "_value * -8" },
       "type": "avg"
      }
     ],
     "query": "meta.id.keyword: localhost AND values.node_network_protocol_type.val:* AND !values.node_network_protocol_type.val:  772",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Interfaces", "gridPos": { "h": 9, "w": 5, "x": 19, "y": 35 } },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_filesystem_free_bytes.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: localhost AND values.node_filesystem_size_bytes: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_filesystem_size_bytes.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: localhost AND values.node_filesystem_size_bytes: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 53 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\npScheduler Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "pScheduler Run Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_runs.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: pscheduler AND meta.id.keyword: localhost AND values.perfsonar_pscheduler_runs: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "pScheduler Archiving Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_archiving.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: pscheduler AND meta.id.keyword: localhost AND values.perfsonar_pscheduler_archiving: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Paused Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_paused.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: pscheduler AND meta.id.keyword: localhost AND values.perfsonar_pscheduler_paused: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Queue Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_http_queue.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: pscheduler AND meta.id.keyword: localhost AND  values.perfsonar_pscheduler_http_queue: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 73 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nClock Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Time offset between local system and reference clock",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Max Offset Seconds",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_timex_offset_seconds.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: localhost",
     "timeField": "@timestamp"
    }
   ]
  },
  { "gridPos": { "h": 5, "w": 24, "x": 0, "y": 84 } }
 ]
}