{
 "title": "perfSONAR Toolkit",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "{\"find\":\"terms\", \"field\":\"meta.uname.nodename.keyword\", \"size\": 1}"
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 1, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.stddev", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_network_speed_bytes.val",
       "id": "1",
       "settings": { "script": "_value * 8" },
       "type": "max"
      },
      {
       "field": "values.node_network_mtu_bytes.val",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "type.keyword: node AND values.node_network_speed_bytes.val: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Tests Run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 1, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "test.type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Tests  Configured by Type",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "test.type.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "type": "cardinality"
      }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "options": {
    "content": "<div class=\"nav-div\">\n<a class=\"simple-button\" href=\"/grafana/d/eb96563b-0d93-4910-be3c-5be331a00339/perfsonar-host-metrics?orgId=1\">Host Info</a>\n</div>\n<div class=\"nav-div\">\n<a class=\"simple-button\" href=\"/grafana/dashboards/f/fd44984e-41df-4659-a60a-67809aa46cd2/external-dashboards\">External Dashboards</a>\n</div>\n<div class=\"nav-div\">\n<a class=\"simple-button\" href=\"/grafana/dashboards/f/d94dcbb1-4076-4c61-b947-3194b3881b65/my-dashboards\">My Dashboards </a>\n</div>\n\n<style>\n  .nav-div {\n    margin:28px 10px; \n    text-align:center;\n  }\n</style>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Test Result Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 1, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "4",
       "settings": {
        "min_doc_count": "1",
        "missing": "-999999",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "5", "type": "min" },
      { "field": "result.packets.loss", "id": "6", "settings": { "missing": "-999999" }, "type": "max" },
      {
       "field": "result.latency.min",
       "id": "7",
       "settings": {},
       "type": "min"
      },
      { "field": "result.rtt", "id": "8", "settings": { "missing": "-999999" }, "type": "min" }
     ],
     "query": "test.type.keyword: throughput OR test.type.keyword: latencybg",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Full Test Listing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "List of Tests",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 1, "y": 33 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pscheduler.test_checksum.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test.type.keyword",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "-",
          "order": "desc",
          "orderBy": "_term",
          "size": "1"
         },
         "type": "terms"
        },
        {
         "field": "meta.source.hostname.keyword",
         "id": "4",
         "settings": {
          "min_doc_count": "1",
          "missing": "-",
          "order": "desc",
          "orderBy": "_term",
          "size": "1"
         },
         "type": "terms"
        },
        {
         "field": "meta.destination.hostname.keyword",
         "id": "5",
         "settings": {
          "min_doc_count": "1",
          "missing": "-",
          "order": "desc",
          "orderBy": "_term",
          "size": "1"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "pscheduler.start_time"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<hr>\n<div style=\"text-align:center\"><a href=\"https://www.perfsonar.net/about/privacy-policy/\">Privacy Policy</a> | <a href=\"http://stats.perfsonar.net/\">Global Node Directory</a> | <a href=\"/toolkit/services/host.cgi?method=get_summary\">Host JSON</a></div>\n<div style=\"padding:10px 10px 10px 10px;text-align:center\"><img style=\"width:30px;\" src=\"public/img/ps_footer_grafana_logo.svg\"/>&nbsp;Powered by Grafana</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  }
 ]
}