{
 "title": "perfSONAR Main",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "{\"find\":\"terms\", \"field\":\"meta.uname.nodename.keyword\", \"query\": \"is_local: true\", \"size\": 1}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\n<img \nsrc=\"/grafana/public/img/perfsonar-logo-white-full.svg\" \nstyle=\"background:rgb(17, 18, 23); width:200px; \"/> \non $node_name\n</text>\n<a class=\"simple-button\" target=\"_blank\" href=\"https://docs.perfsonar.net/\" style=\"float: right;\">? Help</a>\n<a class=\"simple-button\" target=\"_blank\" href=\"/toolkit/auth/admin/\" style=\"float: right;\">Configuration</a>\n<a class=\"simple-button\" href=\"/grafana/d/ff439cb3-6042-43b5-a999-674681d80395/perfsonar-toolkit?orgId=1\" style=\"float: right;\">Home</a>\n</div>\n\n\n<style>\n  /* custom stuff */\n  a.buttons, button.buttons {\n    text-decoration: none;\n    background-color: #1b6522;\n    border: 3px solid white; \n    border-radius: 3px;\n    color: white !important;  \n    font-weight: bold; \n    text-align: right; \n    padding: 10px; \n    width: auto;\n    display: inline-block;\n  }\n  a.simple-button {\n    text-decoration: none;\n    background-color: black;\n    border: 3px solid #1b6522; \n    border-radius: 3px;\n    color: white; \n    font-weight: bold; \n    text-align: right; \n    padding: 10px; \n    width: auto;\n    margin: 0 5px 0 5px;\n  }\n  a.simple-button:hover {\n    color: #1b6522;\n  }\n  h1.title,h2.title,h3.title,div.title {\n    color: #6D6E71; \n    font-weight:bold;\n  }\n  p.description {\n    color: #6D6E71;\n  }\n  a.link {\n    color: #1b6522;\n  }\n\n  /* ----grafana stuff---- */\n  button.css-82ooe6-button, button.css-1pq88ji-button {\n    background-color: rgba(78, 193, 224,0.7);\n    color: white;\n  }\n  button.css-82ooe6-button:hover, button.css-1pq88ji-button:hover {\n    background-color: #1b6522;\n  }\n  button.dashboard-row__title {\n    color: #6D6E71;\n  }\n  /* +add button */\n  button.css-r8pbcf-button-add-panel-button-add-panel-button-text,\n  button.css-1bvfhzx-button-add-panel-button-add-panel-button-text {\n    color: #1b6522;\n    border: 1px solid #1b6522;\n    }\n\n\n  /* ----light mode---- */\n  button.css-14424at {\n    color: #6D6E71; \n  }\n  button.css-14424at:hover {\n    color: #1b6522; \n  }\n    /* data links */\n  div.css-1d09i7b {\n    color: rgb(36, 41, 46);\n  }\n  div.css-1d09i7b:hover {\n    color: #1b6522;\n  }\n\n  /* ----dark mode---- */\n  div.css-1h2bvkc {\n    color: rgb(204, 204, 220);\n  }\n  div.css-1h2bvkc:hover {\n    color: #6d6e71;\n  }\n  button.css-1n3c59t {\n    color: #1b6522;\n  }\n  button.css-1n3c59t:hover {\n    color: #6D6E71;\n  }\n\n  /* data links */\n  div.css-1ijov7j {\n    color: rgb(204, 204, 220);\n  }\n  div.css-1ijov7j:hover {\n    color: #1b6522;\n  }\n  \n</style>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_network_speed_bytes.val",
       "id": "1",
       "settings": { "script": "_value * 8" },
       "type": "max"
      },
      {
       "field": "values.node_network_mtu_bytes.val",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "type.keyword: node AND values.node_network_speed_bytes.val: *",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.labels.address.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "type.keyword: node AND meta.labels.scope.keyword: global",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 1, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.stddev", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Tests  Configured by Type",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "test.type.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "type": "cardinality"
      }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Number of Tests Run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 1, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "test.type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": {
    "content": "<div class=\"nav-div\">\n<a class=\"simple-button\" href=\"/grafana/d/eb96563b-0d93-4910-be3c-5be331a00339/perfsonar-host-metrics?orgId=1\">Host Info</a>\n</div>\n<div class=\"nav-div\">\n<a class=\"simple-button\" href=\"/grafana/dashboards/f/d94dcbb1-4076-4c61-b947-3194b3881b65/\">My Dashboards</a>\n</div>\n\n<style>\n  .nav-div {\n    margin:28px 10px; \n    text-align:center;\n  }\n</style>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Test Result Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 1, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "4",
       "settings": {
        "min_doc_count": "1",
        "missing": "-999999",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "5", "type": "min" },
      { "field": "result.packets.loss", "id": "6", "settings": { "missing": "-999999" }, "type": "max" },
      {
       "field": "result.latency.min",
       "id": "7",
       "settings": {},
       "type": "min"
      },
      {
       "field": "result.rtt.min",
       "id": "8",
       "settings": {},
       "type": "min"
      }
     ],
     "query": "test.type.keyword: throughput OR test.type.keyword: latencybg OR test.type.keyword: rtt",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "pSConfig Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Full Test Listing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "List of Tests",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 1, "y": 34 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "pscheduler.test_checksum.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "test.type.keyword",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "-",
          "order": "desc",
          "orderBy": "_term",
          "size": "1"
         },
         "type": "terms"
        },
        {
         "field": "meta.source.hostname.keyword",
         "id": "4",
         "settings": {
          "min_doc_count": "1",
          "missing": "-",
          "order": "desc",
          "orderBy": "_term",
          "size": "1"
         },
         "type": "terms"
        },
        {
         "field": "meta.destination.hostname.keyword",
         "id": "5",
         "settings": {
          "min_doc_count": "1",
          "missing": "-",
          "order": "desc",
          "orderBy": "_term",
          "size": "1"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "pscheduler.start_time"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "options": {
      "content": "<hr>\n<div style=\"text-align:center\"><a href=\"https://www.perfsonar.net/about/privacy-policy/\">Privacy Policy</a> | <a href=\"http://stats.perfsonar.net/\">Global Node Directory</a> | <a href=\"/toolkit/services/host.cgi?method=get_summary\">Host JSON</a></div>\n<div style=\"padding:10px 10px 10px 10px;text-align:center\"><img style=\"width:30px;\" src=\"public/img/ps_footer_grafana_logo.svg\"/>&nbsp;Powered by Grafana</div>"
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "pscheduler.start_time"
      }
     ]
    }
   ]
  }
 ]
}