{
 "title": "perfSONAR Host Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\":\"terms\", \"field\":\"meta.id.keyword\", \"size\": 1000000}"
   },
   {
    "name": "node_name",
    "query": "{\"find\":\"terms\", \"field\":\"meta.uname.nodename.keyword\", \"query\": \"meta.id: $host\", \"size\": 1}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\n<img \nsrc=\"/grafana/public/img/perfsonar-logo-white-full.svg\" \nstyle=\"background:rgb(17, 18, 23); width:200px; \"/> \non $node_name\n</text>\n<a class=\"simple-button\" target=\"_blank\" href=\"https://docs.perfsonar.net/\" style=\"float: right;\">? Help</a>\n<a class=\"simple-button\" target=\"_blank\" href=\"/toolkit/auth/admin/\" style=\"float: right;\">Configuration</a>\n<a class=\"simple-button\" href=\"/grafana/d/ff439cb3-6042-43b5-a999-674681d80395/perfsonar-main?orgId=1\" style=\"float: right;\">Home</a>\n</div>\n\n\n<style>\n  /* custom stuff */\n  a.buttons, button.buttons {\n    text-decoration: none;\n    background-color: #1b6522;\n    border: 3px solid white; \n    border-radius: 3px;\n    color: white !important;  \n    font-weight: bold; \n    text-align: right; \n    padding: 10px; \n    width: auto;\n    display: inline-block;\n  }\n  a.simple-button {\n    text-decoration: none;\n    background-color: black;\n    border: 3px solid #1b6522; \n    border-radius: 3px;\n    color: white; \n    font-weight: bold; \n    text-align: right; \n    padding: 10px; \n    width: auto;\n    margin: 0 5px 0 5px;\n  }\n  a.simple-button:hover {\n    color: #1b6522;\n  }\n  h1.title,h2.title,h3.title,div.title {\n    color: #6D6E71; \n    font-weight:bold;\n  }\n  p.description {\n    color: #6D6E71;\n  }\n  a.link {\n    color: #1b6522;\n  }\n\n  /* ----grafana stuff---- */\n  button.css-82ooe6-button, button.css-1pq88ji-button {\n    background-color: rgba(78, 193, 224,0.7);\n    color: white;\n  }\n  button.css-82ooe6-button:hover, button.css-1pq88ji-button:hover {\n    background-color: #1b6522;\n  }\n  button.dashboard-row__title {\n    color: #6D6E71;\n  }\n  /* +add button */\n  button.css-r8pbcf-button-add-panel-button-add-panel-button-text,\n  button.css-1bvfhzx-button-add-panel-button-add-panel-button-text {\n    color: #1b6522;\n    border: 1px solid #1b6522;\n    }\n\n\n  /* ----light mode---- */\n  button.css-14424at {\n    color: #6D6E71; \n  }\n  button.css-14424at:hover {\n    color: #1b6522; \n  }\n    /* data links */\n  div.css-1d09i7b {\n    color: rgb(36, 41, 46);\n  }\n  div.css-1d09i7b:hover {\n    color: #1b6522;\n  }\n\n  /* ----dark mode---- */\n  div.css-1h2bvkc {\n    color: rgb(204, 204, 220);\n  }\n  div.css-1h2bvkc:hover {\n    color: #6d6e71;\n  }\n  button.css-1n3c59t {\n    color: #1b6522;\n  }\n  button.css-1n3c59t:hover {\n    color: #6D6E71;\n  }\n\n  /* data links */\n  div.css-1ijov7j {\n    color: rgb(204, 204, 220);\n  }\n  div.css-1ijov7j:hover {\n    color: #1b6522;\n  }\n  \n</style>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 3 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nService Up/Down Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Current Service Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_systemd_unit_state.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: $host AND !meta.labels.name.keyword: perfsonar-generate_motd.service AND !meta.labels.name.keyword: perfsonar-configure_nic_parameters.service AND values.node_systemd_unit_state: * AND meta.labels.state.keyword: active",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "History of perfSONAR Service Status",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_systemd_unit_state.val",
       "id": "1",
       "type": "min"
      }
     ],
     "query": "meta.id.keyword: $host AND !meta.labels.name.keyword: perfsonar-generate_motd.service AND !meta.labels.name.keyword: perfsonar-configure_nic_parameters.service AND values.node_systemd_unit_state: * AND meta.labels.state.keyword: active",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 15 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nLookup Sevice Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "perfSONAR Installation",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.type.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "meta.labels.version.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "values.perfsonar_bundle.val: 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "History of Lookup Service Registration",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Registration Status",
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_host_registered.val",
       "id": "1",
       "type": "min"
      }
     ],
     "query": "meta.id.keyword: $host ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Lookup Service Client Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.id.keyword: $host AND values.perfsonar_host_registered.val: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 20 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nHost Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_memory_MemAvailable_bytes.val",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.node_memory_MemTotal_bytes.val",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.os.pretty_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.uname.release.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.uname.machine.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.id.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.cpu.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_softnet_processed_total.rate",
       "id": "1",
       "settings": { "percents": [ "50" ] },
       "type": "percentiles"
      }
     ],
     "query": "meta.id.keyword: $host AND values.node_softnet_processed_total: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "CPU Utilization",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_cpu_seconds_total.rate",
       "id": "1",
       "settings": { "script": "1 - _value" },
       "type": "avg"
      }
     ],
     "query": "meta.id.keyword: $host AND meta.labels.mode.keyword: idle",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IP Addresses",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_network_speed_bytes.val",
       "id": "1",
       "settings": { "script": "_value * 8" },
       "type": "max"
      },
      {
       "field": "values.node_network_mtu_bytes.val",
       "id": "3",
       "type": "max"
      }
     ],
     "query": "type.keyword: node AND values.node_network_speed_bytes.val: *",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.labels.address.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "type.keyword: node AND meta.labels.scope: global",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "{{term meta.labels.device.keyword}} Incoming Traffic",
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_network_receive_bytes_total.rate",
       "id": "1",
       "settings": { "script": "_value * 8" },
       "type": "avg"
      }
     ],
     "query": "meta.id.keyword: $host AND values.node_network_protocol_type.val:* AND !values.node_network_protocol_type.val:  772",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term meta.labels.device.keyword}} Outgoing Traffic",
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_network_transmit_bytes_total.rate",
       "id": "1",
       "settings": { "script": "_value * -8" },
       "type": "avg"
      }
     ],
     "query": "meta.id.keyword: $host AND values.node_network_protocol_type.val:* AND !values.node_network_protocol_type.val:  772",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.node_filesystem_size_bytes.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: $host AND values.node_filesystem_size_bytes: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_filesystem_free_bytes.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: $host AND values.node_filesystem_size_bytes: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 58 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\npScheduler Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "pScheduler Run Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_runs.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: perfsonar_host AND meta.id.keyword: $host AND values.perfsonar_pscheduler_runs: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "pScheduler Archiving Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_archiving.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: perfsonar_host AND meta.id.keyword: $host AND values.perfsonar_pscheduler_archiving: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Paused Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_paused.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: perfsonar_host AND meta.id.keyword: $host AND values.perfsonar_pscheduler_paused: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Queue Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_pscheduler_http_queue.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "type.keyword: perfsonar_host AND meta.id.keyword: $host AND  values.perfsonar_pscheduler_http_queue: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 78 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\npSConfig Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "pSConfig pScheduler Agent Last Run",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.guid.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.perfsonar_psconfig_pscheduler_agent_end_time.val",
       "id": "1",
       "settings": { "script": "_value * 1000" },
       "type": "max"
      },
      {
       "field": "values.perfsonar_psconfig_pscheduler_agent_start_time.val",
       "id": "3",
       "settings": { "script": "_value * 1000" },
       "type": "max"
      },
      {
       "id": "6",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "3" }
       ],
       "settings": { "script": "params.var2 - params.var1" },
       "type": "bucket_script"
      }
     ],
     "query": "meta.id.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "pSConfig pScheduler Agent Remote URLs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.labels.url.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.labels.configure_archives.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "meta.id.keyword: $host AND values.perfsonar_psconfig_pscheduler_remote.val: 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 90 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nClock Metrics\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Time offset between local system and reference clock",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Max Offset Seconds",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_timex_offset_seconds.val",
       "id": "1",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 101 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\nHost Tuning Settings\n</text>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Tuning Settings",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.node_sysctl_net_core_netdev_max_backlog.val",
       "id": "1",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_core_rmem_default.val",
       "id": "3",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_core_rmem_max.val",
       "id": "4",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_core_wmem_default.val",
       "id": "5",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_core_wmem_max.val",
       "id": "6",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_conf_all_arp_announce.val",
       "id": "7",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_conf_all_arp_filter.val",
       "id": "8",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_conf_all_arp_ignore.val",
       "id": "9",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_conf_default_arp_filter.val",
       "id": "10",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_mtu_probing.val",
       "id": "11",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_no_metrics_save.val",
       "id": "12",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_rmem_default.val",
       "id": "13",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_rmem_max.val",
       "id": "14",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_rmem_min.val",
       "id": "15",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_wmem_default.val",
       "id": "16",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_wmem_max.val",
       "id": "17",
       "type": "max"
      },
      {
       "field": "values.node_sysctl_net_ipv4_tcp_wmem_min.val",
       "id": "18",
       "type": "max"
      }
     ],
     "query": "meta.id.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Congestion Contol Settings",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 9, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "18", "type": "logs" }
     ],
     "query": "meta.id.keyword: $host AND values.node_sysctl_info.val: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "options": {
    "content": "<hr>\n<div style=\"text-align:center\"><a href=\"https://www.perfsonar.net/about/privacy-policy/\">Privacy Policy</a> | <a href=\"http://stats.perfsonar.net/\">Global Node Directory</a> | <a href=\"/toolkit/services/host.cgi?method=get_summary\">Host JSON</a></div>\n<div style=\"padding:10px 10px 10px 10px;text-align:center\"><img style=\"width:30px;\" src=\"public/img/ps_footer_grafana_logo.svg\"/>&nbsp;Powered by Grafana</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  }
 ]
}