{
 "title": "perfSONAR Endpoint Pair Explorer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Archive", "query": "grafana-opensearch-datasource" },
   {
    "name": "source",
    "label": "Source Host",
    "query": "{\"find\":\"terms\", \"field\":\"meta.source.hostname.keyword\", \"size\": 10000000}"
   },
   {
    "name": "dest",
    "label": "Destination Host",
    "query": "{\"find\":\"terms\", \"field\":\"meta.destination.hostname.keyword\", \"query\": \"meta.source.hostname.keyword: $source\", \"size\": 10000000}"
   },
   {
    "name": "source_ref",
    "query": "{\"find\": \"terms\", \"field\":\"reference.display-set-source.keyword\", \"query\":\"test.spec.source.keyword:$source\", \"size\": 10000000}"
   },
   {
    "name": "dest_ref",
    "query": "{\"find\": \"terms\", \"field\":\"reference.display-set-dest.keyword\",  \"query\":\"test.spec.dest.keyword:$dest\", \"size\": 10000000}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n<text style=\"font-size:20pt;\">\n<img \nsrc=\"/grafana/public/img/perfsonar-logo-white-full.svg\" \nstyle=\"background:rgb(17, 18, 23); width:200px; \"/>\n</text>\n<a class=\"simple-button\" target=\"_blank\" href=\"https://docs.perfsonar.net/\" style=\"float: right;\">? Help</a>\n<a class=\"simple-button\" target=\"_blank\" href=\"/toolkit/auth/admin/\" style=\"float: right;\">Configuration</a>\n<a class=\"simple-button\" href=\"/grafana/d/ff439cb3-6042-43b5-a999-674681d80395/perfsonar-main?orgId=1\" style=\"float: right;\">Home</a>\n</div>\n\n\n<style>\n  /* custom stuff */\n  a.buttons, button.buttons {\n    text-decoration: none;\n    background-color: #1b6522;\n    border: 3px solid white; \n    border-radius: 3px;\n    color: white !important;  \n    font-weight: bold; \n    text-align: right; \n    padding: 10px; \n    width: auto;\n    display: inline-block;\n  }\n  a.simple-button {\n    text-decoration: none;\n    background-color: black;\n    border: 3px solid #1b6522; \n    border-radius: 3px;\n    color: white; \n    font-weight: bold; \n    text-align: right; \n    padding: 10px; \n    width: auto;\n    margin: 0 5px 0 5px;\n  }\n  a.simple-button:hover {\n    color: #1b6522;\n  }\n  h1.title,h2.title,h3.title,div.title {\n    color: #6D6E71; \n    font-weight:bold;\n  }\n  p.description {\n    color: #6D6E71;\n  }\n  a.link {\n    color: #1b6522;\n  }\n\n  /* ----grafana stuff---- */\n  button.css-82ooe6-button, button.css-1pq88ji-button {\n    background-color: rgba(78, 193, 224,0.7);\n    color: white;\n  }\n  button.css-82ooe6-button:hover, button.css-1pq88ji-button:hover {\n    background-color: #1b6522;\n  }\n  button.dashboard-row__title {\n    color: #6D6E71;\n  }\n  /* +add button */\n  button.css-r8pbcf-button-add-panel-button-add-panel-button-text,\n  button.css-1bvfhzx-button-add-panel-button-add-panel-button-text {\n    color: #1b6522;\n    border: 1px solid #1b6522;\n    }\n\n\n  /* ----light mode---- */\n  button.css-14424at {\n    color: #6D6E71; \n  }\n  button.css-14424at:hover {\n    color: #1b6522; \n  }\n    /* data links */\n  div.css-1d09i7b {\n    color: rgb(36, 41, 46);\n  }\n  div.css-1d09i7b:hover {\n    color: #1b6522;\n  }\n\n  /* ----dark mode---- */\n  div.css-1h2bvkc {\n    color: rgb(204, 204, 220);\n  }\n  div.css-1h2bvkc:hover {\n    color: #6d6e71;\n  }\n  button.css-1n3c59t {\n    color: #1b6522;\n  }\n  button.css-1n3c59t:hover {\n    color: #6D6E71;\n  }\n\n  /* data links */\n  div.css-1ijov7j {\n    color: rgb(204, 204, 220);\n  }\n  div.css-1ijov7j:hover {\n    color: #1b6522;\n  }\n  \n</style>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.retransmits", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.retransmits", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "95th percentile - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.p_95",
       "hide": true,
       "id": "1",
       "type": "max"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Median - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.median",
       "hide": true,
       "id": "1",
       "type": "max"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Min - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.min",
       "hide": true,
       "id": "1",
       "type": "min"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": ".001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Latency (Reverse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "95th percentile - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.p_95",
       "hide": true,
       "id": "1",
       "type": "max"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Median - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.median",
       "hide": true,
       "id": "1",
       "type": "max"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Min - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.min",
       "hide": true,
       "id": "1",
       "type": "min"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Packet Loss (Reverse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Standard Deviation - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.stddev",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Variance - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.variance",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * ((params.bucket_width * params.bucket_width) / (0.001 * 0.001))"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Interquartile Range - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.p_75",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "result.latency.p_25",
       "hide": true,
       "id": "8",
       "type": "avg"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "9",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "10",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "8" },
        { "name": "bucket_width", "pipelineAgg": "9" }
       ],
       "settings": {
        "script": "(params.var1 - params.var2) * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Jitter (Reverse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Standard Deviation - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.stddev",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Variance - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.variance",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "8",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "latency", "pipelineAgg": "1" },
        { "name": "bucket_width", "pipelineAgg": "8" }
       ],
       "settings": {
        "script": "params.latency * ((params.bucket_width * params.bucket_width) / (0.001 * 0.001))"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Interquartile Range - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.p_75",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "result.latency.p_25",
       "hide": true,
       "id": "8",
       "type": "avg"
      },
      {
       "field": "test.spec.bucket-width",
       "hide": true,
       "id": "9",
       "settings": { "missing": "0.001" },
       "type": "max"
      },
      {
       "id": "10",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "8" },
        { "name": "bucket_width", "pipelineAgg": "9" }
       ],
       "settings": {
        "script": "(params.var1 - params.var2) * (params.bucket_width / 0.001)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "(test.type.keyword:latencybg OR test.type.keyword:latency) AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum- {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.rtt.min", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword:rtt AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Mean - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.rtt.mean", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:rtt AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.rtt.max", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:rtt AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "RTT Reverse",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum- {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.rtt.min", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword:rtt AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Mean - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.rtt.mean", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:rtt AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.rtt.max", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:rtt AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Traceroute Hop Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.hop.count", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:trace AND (meta.source.hostname.keyword:$source OR reference.display-set-source.keyword:$source_ref) AND (meta.destination.hostname.keyword:$dest OR reference.display-set-dest.keyword:$dest_ref)",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.hop.count", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:trace AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Traceroute Unique Results",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "result.hop.ip_str.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "test.type.keyword:trace AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Traceroute Unique Results (Reverse)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "result.hop.ip_str.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "test.type.keyword:trace AND (meta.source.hostname.keyword:$dest OR reference.display-set-source.keyword:$dest_ref) AND (meta.destination.hostname.keyword:$source OR reference.display-set-dest.keyword:$source_ref)",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Advanced Displays",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Results (Max 500)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_data"
        }
       ],
       "query": "meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
       "timeField": "pscheduler.start_time"
      }
     ]
    },
    {
     "title": "Raw Results Reverse (Max 500)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_data"
        }
       ],
       "query": "meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
       "timeField": "pscheduler.start_time"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "options": {
      "content": "<hr>\n<div style=\"text-align:center\"><a href=\"https://www.perfsonar.net/about/privacy-policy/\">Privacy Policy</a> | <a href=\"http://stats.perfsonar.net/\">Global Node Directory</a> | <a href=\"/toolkit/services/host.cgi?method=get_summary\">Host JSON</a></div>\n<div style=\"padding:10px 10px 10px 10px;text-align:center\"><img style=\"width:30px;\" src=\"public/img/ps_footer_grafana_logo.svg\"/>&nbsp;Powered by Grafana</div>"
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "pscheduler.start_time"
      }
     ]
    }
   ]
  }
 ]
}