{
 "title": "perfSONAR Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 0 },
   "options": {
    "content": "<center>\n<img src=\"https://raw.githubusercontent.com/perfsonar/grafana/bd0e10b944499ee252b0fa7dbfb2cb45c4a23642/examples/images/perfsonar-logo-white-transparent-200.png\">\n</center>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Packet Loss Over Time by Sender",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 20, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Maximum Packet Loss",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 12, "w": 8, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword: latencybg",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Highest Average Packet Loss by Sender",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword: latencybg",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Highest Average Packet Loss by Receiver",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.destination.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword: latencybg",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Minimum Throughput",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 12, "w": 8, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword: throughput",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Lowest Minimum Throughput by Sender",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword: throughput",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Lowest Minimum Throughput by Receiver",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.destination.hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword: throughput",
     "timeField": "pscheduler.start_time"
    }
   ]
  }
 ]
}