{
 "title": "perfSONAR Endpoint Pair Explorer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Archive", "query": "grafana-opensearch-datasource" },
   {
    "name": "node_name",
    "query": "{\"find\":\"terms\", \"field\":\"meta.uname.nodename.keyword\", \"size\": 1}"
   },
   {
    "name": "source",
    "label": "Source Host",
    "query": "{\"find\":\"terms\", \"field\":\"meta.source.hostname.keyword\", \"size\": 10000000}"
   },
   {
    "name": "dest",
    "label": "Destination Host",
    "query": "{\"find\":\"terms\", \"field\":\"meta.destination.hostname.keyword\", \"query\": \"meta.source.hostname.keyword: $source\", \"size\": 10000000}"
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.throughput", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.retransmits", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "{{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.retransmits", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:throughput AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "95th percentile - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.p_95", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Median - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.median", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Min - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.min", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Latency (Reverse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "95th percentile - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.p_95", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Median - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.median", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Min - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.min", "id": "1", "type": "min" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Packet Loss (Reverse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.packets.loss", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Standard Deviation - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.stddev", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Variance - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.variance", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Interquartile Range - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.p_75",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "result.latency.p_25",
       "hide": true,
       "id": "8",
       "type": "avg"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "8" }
       ],
       "settings": { "script": "params.var1 - params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Jitter (Reverse)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Standard Deviation - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.stddev", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Variance - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.latency.variance", "id": "1", "type": "avg" }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Interquartile Range - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result.latency.p_75",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "result.latency.p_25",
       "hide": true,
       "id": "8",
       "type": "avg"
      },
      {
       "id": "9",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "8" }
       ],
       "settings": { "script": "params.var1 - params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "test.type.keyword:latencybg AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Traceroute Hop Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.hop.count", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:trace AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    },
    {
     "alias": "Max - {{term meta.source.hostname.keyword}} -> {{term meta.destination.hostname.keyword}} ({{term pscheduler.tool.keyword}}) - IPv{{term meta.ip_version}}",
     "bucketAggs": [
      {
       "field": "pscheduler.test_checksum.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.ip_version",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "pscheduler.start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "result.hop.count", "id": "1", "type": "max" }
     ],
     "query": "test.type.keyword:trace AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Traceroute Unique Results",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "result.hop.ip_str.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "test.type.keyword:trace AND meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Traceroute Unique Results (Reverse)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.source.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.destination.hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "pscheduler.tool.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "result.hop.ip_str.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "test.type.keyword:trace AND meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
     "timeField": "pscheduler.start_time"
    }
   ]
  },
  {
   "title": "Advanced Displays",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Results (Max 500)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_data"
        }
       ],
       "query": "meta.source.hostname.keyword:$source AND meta.destination.hostname.keyword:$dest",
       "timeField": "pscheduler.start_time"
      }
     ]
    },
    {
     "title": "Raw Results Reverse (Max 500)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_data"
        }
       ],
       "query": "meta.source.hostname.keyword:$dest AND meta.destination.hostname.keyword:$source",
       "timeField": "pscheduler.start_time"
      }
     ]
    },
    { "gridPos": { "h": 6, "w": 24, "x": 0, "y": 123 } }
   ]
  }
 ]
}